version: '3'

services:

  dashboard-postgres:
    image: postgres
    container_name: dashboard-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../postgres/postgres-data:/var/lib/postgresql/data:consistent
    logging:
      options:
        max-size: "50m"

  dashboard-app:
    build: ../app
    container_name: dashboard-app
    depends_on:
      - dashboard-postgres
    restart: always
    expose:
      - 80
    ports:
      - "80:80"
    environment:
      - POSTGRES_HOST=dashboard-postgres
    logging:
      options:
        max-size: "50m"